Repository AY2223S2-CS2103T-W12-4/tp, pull requests merged in 2023-03, with the labels that each got.

#29 Improve find command to also search in patient details
  src/main/java/seedu/address/model/patient/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/test/java/seedu/address/model/patient/NameContainsKeywordsPredicateTest.java
Labels: type.Task, priority.High

#32 Create appointment model
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/Description.java
  src/main/java/seedu/address/model/appointment/Timeslot.java
  src/test/java/seedu/address/model/appointment/AppointmentTest.java
  src/test/java/seedu/address/model/appointment/DescriptionTest.java
  src/test/java/seedu/address/model/appointment/TimeslotTest.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
Labels: priority.High, type.Appointment

#34 Implement find for all patient details
  src/main/java/seedu/address/logic/commands/FindDetailsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindDetailsCommandParser.java
  src/main/java/seedu/address/model/patient/DetailsContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/patient/NameContainsKeywordsPredicate.java
Labels: type.Story, type.Task, priority.High

#33 add id
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/id/AppointmentId.java
  src/main/java/seedu/address/model/id/Id.java
  src/main/java/seedu/address/model/id/PatientId.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPatientTest.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/PatientUtil.java
Labels: type.Task, priority.High

#45 Edit appointment
  .gitignore
  docs/images/github-icon.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/ListAppointmentsCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyPatientList.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/Timeslot.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/main/java/seedu/address/model/id/AppointmentId.java
  src/main/java/seedu/address/model/id/PatientId.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/AppointmentListStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonAppointmentListStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/JsonSerializableAppointmentList.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
  src/test/java/seedu/address/testutil/AppointmentListBuilder.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/TypicalAppointments.java
Labels: priority.High, type.Appointment

#48 Delete appointment
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteAppointmentCommandParser.java
  src/main/java/seedu/address/model/Model.java
Labels: priority.High, type.Appointment

#51 Add find command to DG, update model and storage diagrams
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/BetterModelClassDiagram-0.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/address/logic/commands/FindDetailsCommand.java
  src/main/java/seedu/address/logic/parser/FindDetailsCommandParser.java
  src/main/java/seedu/address/model/AppointmentList.java
  src/main/java/seedu/address/model/patient/DetailsContainKeywordsPredicate.java
Labels: documentation

#53 Add Appointment Command
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, type.Appointment

#61 Implement find for a specified time period
  src/main/java/seedu/address/logic/commands/FindAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/ListAppointmentsCommand.java
  src/main/java/seedu/address/logic/parser/FindAppointmentCommandParser.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/AppointmentDuringTimePredicate.java
  src/main/java/seedu/address/model/appointment/Timeslot.java
  src/main/java/seedu/address/ui/AppointmentCard.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
Labels: priority.High, type.Appointment

#63 Implement cascade for delete patient
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
Labels: type.Task

#71 Update UG
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#77 Update JSON storage information in UG
  docs/UserGuide.md
  docs/images/Ui.png
Labels: documentation

#76 Update DG with edit, edit_appt and find_appt commands
  docs/DeveloperGuide.md
Labels: documentation

#74 Add quick start explanation for new users
  docs/UserGuide.md
Labels: documentation

#80 Update UG to make it more user-friendly
  docs/UserGuide.md
Labels: documentation

#82 Fix delete appointment command format usage
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
Labels: documentation

#86 Improve DG based on feedback
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/images/BetterModelClassDiagram-0.png
  docs/images/BetterModelClassDiagram.png
Labels: documentation

#85 Implement today command
  src/main/java/seedu/address/logic/commands/FindAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/TodayCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/AppointmentDuringTimePredicate.java
  src/main/java/seedu/address/model/appointment/AppointmentHasOverlapPredicate.java
  src/main/java/seedu/address/model/appointment/Timeslot.java
Labels: bug, type.Task

#89 Fix command names and examples
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindDetailsCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: bug

#91 Remove functionality to edit names of patients
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/patient/UniquePatientList.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPatientDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPatientDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PatientUtil.java
Labels: enhancement

#97 Update UG
  docs/UserGuide.md
Labels: documentation
