Repository AY2223S2-CS2103T-W12-4/tp, pull requests merged in 2023-04, with the labels that each got.

#146 Fix bugs from PE
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/ui/CalendarCard.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/UiManager.java
Labels: bug, documentation

#151 Fix issue #111 - correct error message for delete appointment
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
Labels: bug

#152 Fix issue #104 - Allow an optional single space in timeslot after comma
  src/main/java/seedu/address/model/appointment/Timeslot.java
Labels: enhancement

#154 Add app maximization instruction
  README.md
  docs/UserGuide.md
Labels: bug

#182 Calendar bug fix
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/FindAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/ListAppointmentsCommand.java
  src/main/java/seedu/address/ui/CalendarCard.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: bug

#183 Update DG with add_patient and add_appt
  docs/DeveloperGuide.md
  docs/diagrams/AddAppointmentParserSequenceDiagram.puml
  docs/diagrams/AddAppointmentSequenceDiagram.puml
  docs/diagrams/AddPatientParserSequenceDiagram.puml
  docs/diagrams/AddPatientSequenceDiagram.puml
  docs/images/AddAppointmentParserSequenceDiagram.png
  docs/images/AddAppointmentSequenceDiagram.png
  docs/images/AddPatientParserSequenceDiagram.png
  docs/images/AddPatientSequenceDiagram.png
Labels: documentation

#184 Fix minor DG bugs
  docs/DeveloperGuide.md
Labels: documentation

#185 Update DG
  README.md
  docs/DeveloperGuide.md
  docs/images/Ui.png
  docs/images/v1.4_jar.png
Labels: documentation

#187 Add annotations to UI
  docs/UserGuide.md
Labels: documentation

#190 Add known feature flaws to DG, fix UG bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#193 Fix UG command summary bugs
  docs/UserGuide.md
Labels: documentation

#194 Add today command to UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation
